### PR TITLE
Adding Chapter 3 content for 10/4/2023 meeting

### PR DESCRIPTION
**Pull request by AmandaRP**

### CODE REVIEW

**Review by jonthegeek — DISMISSED** [review]
This looks great! We'll have to see how things go with the book, though; we might want to accelerate a move to (cached) quarto for this club if the notes won't build!

**Comment by AmandaRP** [comment]
Right, I forgot that cuda operations won't work in the GiHub workflow. Theoretically the book examples can all be run on CPU. I'll comment out a couple of cuda specific lines of code and re-submit a pull request.

**Comment by AmandaRP** [comment]
Right, I forgot that cuda operations won't work with the GitHub workflow. I'll comment out a couple of cuda-specific lines of code and re-submit the PR.

**Comment by jonthegeek** [comment]
@AmandaRP Run this at your command line, and push the resulting DESCRIPTION (or you can add torch directly, but it's good to get in the habit of usethis workflows!)

```
usethis::use_package("torch")
```

It definitely won't build without that, and we'll likely have to update the GHA to tell it to install torch. I'll pull up some of my torch-using remind myself how that works...

**Review by jonthegeek — CHANGES_REQUESTED** [review]
Is it possible to *not* use the okc dataset in the notes (either by not actually rendering whatever you do with it, or by switching to a different dataset)? It was deprecated due to concerns with the data. It's one thing for the book to use it, but we shouldn't propagate the issues (and installing the old version is a huge pain).

**Comment by AmandaRP** [comment]
Gotcha. I'll look at using a different dataset.

**Review by jonthegeek — DISMISSED** [review]
Sweet, thanks! Now we just need to get it to actually build...

**Comment by AmandaRP** [comment]
Looks like `install_torch()` needs to be run at some point in the process.

**Comment by AmandaRP** [comment]
@jonthegeek , Where in the repo would it be best to add the `torch::install_torch()` command? Also, where in the GitHub workflow does R package installation occur? (I didn't see `install.packages()` commands in the repo.)

**Comment by jonthegeek** [comment]
@AmandaRP I'm so sorry, this fell off my to-do list! I'm pretty sure I've gotten torch working in GHA before, so I'll spend the next hour or two sorting this out (I hope)!

**Comment by AmandaRP** [comment]
OK, no rush! I was just looking at it too see if I should do something, but wasn't sure the best approach. Thanks for your help!

**Review by jonthegeek — APPROVED** [review]
This *should* fix it!

**Pull request merged**
